version: '3.8'

services:
  api:
    container_name: todo-api
    build: ../api
    ports:
      - "3000:3000"
    volumes:
      - ../api/src:/app/src
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/todos
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  mongodbdata:
